brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoListListView,
)

urlpatterns = [
    path("", TodoListListView.as_view(), name="todo_list_list"),
]

todos/models.py
from django.db import models


# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.views.generic.list import ListView
from todos.models import TodoList


# Create your views here.
class TodoListListView(ListView):
    model = TodoList
    template_name = "todo_lists/list.html"

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Todo Lists</title>
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

todos/templates/todo_lists/list.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <h1>My Lists</h1>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                    </tr>
                </thead>
                <tbody>
                    {% for list in todolist_list %}
                        <tr>
                            <td>{{ list.name }}</td>
                            <td>{{ list.items.all|length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock content %}